name: Deploy Next.js to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4
      # Step 2: Setup Node.js and pnpm
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v3
        with:
          node-version: 22
          install-pnpm: true
      # Step 3: Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # Step 4: Build the static site and create .nojekyll file
      - name: Build the static site
        run: |
          pnpm build
          # Create .nojekyll to prevent GitHub Pages from ignoring certain files
          touch out/.nojekyll
          # Ensure all built files (including assets) are added for deployment
          git add out/
          git commit --no-verify -m "Deploy static site to GitHub Pages"
      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out # Using 'out' directly for GitHub Pages deployment
