name: Deploy Next.js to GitHub Pages
on:
  push:
    branches:
      - main # Deploy only when changes are pushed to the main branch
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4
      # Step 2: Setup Node.js and pnpm
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v3
        with:
          node-version: 18 # Use the Node.js version required by your project
          install-pnpm: true # Installs pnpm
      # Step 3: Install dependencies
      - name: Install dependencies
        run: pnpm install
      # Step 4: Build and export the static site
      - name: Build and export
        run: |
          pnpm build
          pnpm export
          mv out public
      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
